<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' notifications' => '',
    '-- Choose Subjects --' => '',
    '-- Select Category --' => '',
    '-- Select City --' => '',
    '-- Select Country --' => '',
    '-- Select Region --' => '',
    '--- Select City ---' => '',
    '--- Select Region ---' => '',
    '<i class="fa fa-remove"></i> Delete' => '',
    'ABOUT US' => '',
    'Learn more ' => '',
    'About' => 'ABOUT',
    'Add Category' => '',
    'Add City' => '',
    'Add Country' => '',
    'Add Main Category' => '',
    'Add Region' => '',
    'Add Subject Report' => '',
    'Are you sure you want to delete this item ?' => '',
    'Are you sure you want to delete this item and other?' => '',
    'Are you sure you want to delete this item?' => '',
    'Back' => '',
    'CAREERS' => '',
    'CONTACT US' => '',
    'Categories' => '',
    'Category' => '',
    'Checked' => '',
    'City' => '',
    'Classified ID' => '',
    'Classified Reports' => '',
    'Classifieds' => '',
    'Content' => '',
    'Content Hy' => '',
    'Country' => '',
    'Country Name' => '',
    'Course' => '',
    'Course ID' => '',
    'Create' => '',
    'Create At' => '',
    'Create Classified' => '',
    'Create Classified Report' => '',
    'Create Enroll' => '',
    'Create Pages' => '',
    'Create Subjects' => '',
    'Date of Birth' => '',
    'Delete' => '',
    'Description' => '',
    'Description Hy' => '',
    'Dob' => '',
    'EDUCATION' => '',
    'Email' => '',
    'Email Reporter' => '',
    'Enroll' => '',
    'Enroll in our courses' => '',
    'Enroll now' => '',
    'Enrolls' => '',
    'Firstname' => '',
    'GITC' => '',
    'gitc' => 'GYUMRI INFORMATION TECHNOLOGIES CENTER',
    'GYUMRI INFORMATION TECHNOLOGIES CENTER' => 'GYUMRI <br>INFORMATION <br>TECHNOLOGIES CENTER',
    'GITC_INFO' => 'Gyumri Information Technologies Center (GITC) is an educational foundation in the
                Information
                Technology
                field. Since its establishment, the Center has decentralized the information technology market from
                Yerevan to Gyumri, which is in the northern part of Armenia, contributing to the strengthening of
                the
                economy and progress in the IT sector.
                The Foundation offers education program in Web Technologies and Mobile
                Technologies departments. Instructors are selected from the Yerevan’s best programming and high-tech
                companies.',
    'HISTORY' => '',
    'HOME' => '',
    'ID' => '',
    'Icon' => '',
    'Image' => '',
    'Is Status' => '',
    'It’s important not to give someone a fish to eat, but to teach him how to fish for himself.' => '',
    'Keywords' => '',
    'Keywords Hy' => '',
    'Lastname' => '',
    'List Category' => '',
    'List City' => '',
    'List Country' => '',
    'List Main Category' => '',
    'List Region' => '',
    'List Subject Report' => '',
    'MISSION' => '',
    'Main Category' => '',
    'Message' => 'Message',
    'media' => 'Media about us',
    'Name' => '',
    'No subjects selected' => '',
    'No, break the rules' => '',
    'OBJECTIVES' => '',
    'PARTNERS' => '',
    'Pages' => '',
    'Phone' => '',
    'Price' => '',
    'Products' => '',
    'Region' => '',
    'Region Name' => '',
    'Reset' => '',
    'Review View Classified' => '',
    'SPONSORS' => '',
    'Save' => '',
    'Search' => '',
    'Slug' => '',
    'Status' => '',
    'Subject' => '',
    'Subject Reports' => '',
    'Subjects' => '',
    'Thanks' => '',
    'Employed' => 'Employed',
    'Opinion of Students' => 'Opinion of Students',
    'Our Students Work' => 'Companies filled with our students',
    'Current Courses' => 'Current Courses',
    'Suggested Courses' => 'Suggested Courses',
    'Signature' => 'GITC is 12 years Old...Changing lives in Gyumri',
    'Target benefits' => 'Target Benefits',
    'Applicants' => 'Applicants',
    'Students' => 'Students',
    'Worker' => 'Worker',
    'Unemployed' => 'Unemployed',
    'Thanks for enrolling in our courses. We will contact you soon!' => '',
    'The vision of GITC is:
                To decentralize the information and high-tech industry from the capital to the region,
                promoting economic development and decreasing the migration of workers from Gyumri. ' => '',
    'This saying was inspirational to the donors, whose combined efforts founded Gyumri Information
                Technologies Center Educational Foundation in 2005. The first stage was made possible by the
                generosity
                of Patrick Sarkissian, the founder and chief executive officer of Sarkissian Mason, Fund for
                Armenian
                Relief, Enterprise Incubator Foundation, Shirak Technologies Ltd, loyal members of the Armenian
                Diaspora
                and local donors. They had faith that future generations will build upon the GITC cornerstone with
                diligence and purpose.The work started in small space of 60 square meters, with two employees and
                five
                computers. As soon as information about the Center’s activities became public, more than 20 local
                university graduates rushed to apply to study at the Center.' => '',
    'Title' => '',
    'Title Hy' => '',
    'To increase the opportunities of e-society promoting the development
                    of modern technologies in all social spheres' => '',
    'To prepare specialists demanded by the current IT market' => '',
    'To promote employment and business development by creating attractive
                    conditions and terms for international and local investment' => '',
    'To supplement the main teaching program with short term IT-based and programming-
                    based courses in response to current market demand' => '',
    'To which course you want to enroll?' => '',
    'Type' => '',
    'Update' => '',
    'Update : ' => '',
    'Update At' => '',
    'Update Category' => '',
    'Update Country' => '',
    'Update Main Category' => '',
    'Update Subject Report' => '',
    'Update {modelClass}: ' => '',
    'User ID' => '',
    'VISION' => '',
    'View Category' => '',
    'View City' => '',
    'View Country' => '',
    'View Main Category' => '',
    'View Region' => '',
    'View Subject Report' => '',
    'WELCOME TO GITC!' => '',
    'Yes, break the rules' => '',
    'You have ' => '',
    'You have No notifications' => '',
    'Our Staff' => 'Our Staff',
    'Our Trainers' => 'Our Trainers',
    'About page' => 'Gyumri Information Technologies Center (GITC) is an educational foundation in the Information Technology field. Since its establishment, the Center has decentralized the information technology market from Yerevan to Gyumri, which is in the northern part of Armenia, contributing to the strengthening of the economy and progress in the IT sector. The Foundation offers a two-year postgraduate education program in Web Technologies and Mobile Technologies departments. Instructors are selected from the Yerevan’s best programming and high-tech companies. GITC GTech Solutions skilled team is providing a variety of services in the field of programming and IT. With generous support from its donors, the center is equipped with modern computers, technical equipment and literature. Through its flexible and consistent practical training program, 
                     GITC’s graduates are competitive in the IT labor market.',
    'hy' => 'հայերեն',
    'am' => 'հայ',
    'ru' => 'русский',
//    'en' => 'English',
    'en' => 'Eng',
    'de' => 'Deutsch',
    'fr' => 'Français',
    'Work Experience' => 'Work Experience',
    'Education' => 'Education',
    'Professional Skills' => 'Professional Skills',
    'Interests' => 'Interests',
    'Results' => 'Results',

    'download  resume of alumni' => 'download  resume of alumni',
    'Alumni' => 'Alumni',
    'Mobile programming' => 'Mobile programming',
    'Software programming' => 'Software  programming',
    'GITC in' => 'GITC in Armenia',
    'um' => '',
];
