$(document).ready(function(){$(document).on('click','.lng',function(e){var lang=$(this).attr('id');e.preventDefault();$.post('/site/language',{'_csrf':yii.getCsrfToken(),'lang':lang},function(data){location.reload();})});$(".drop-down .selected div").click(function(){$(".drop-down .options ul").toggle();});$(".drop-down .options ul li i").click(function(){var text=$(this).html();$(".drop-down .selected div span").html(text);$(".drop-down .options ul").hide();});});
$(document).ready(function(){$owl=$(".owl-carousel");if($owl.length>0){$owl.owlCarousel({margin:0,loop:true,autoplay:true,autoplayHoverPause:true,responsive:{0:{items:3},600:{items:6},1000:{items:9}}});}
bannerHeight();$sTS=8;if($('.media_tv').length>0){$sTS=3;}
$('.gitc_trainings, .media_tv').slick({autoplay:false,vertical:true,slidesToShow:$sTS,arrows:true,verticalSwiping:true,slidesToScroll:2,nextArrow:$('.pagerNavigation .bottom'),prevArrow:$('.pagerNavigation .top'),responsive:[{breakpoint:756,settings:{slidesToShow:2,slidesToScroll:2,infinite:true}}]});$('.slider-for').slick({slidesToShow:1,slidesToScroll:1,fade:true,asNavFor:'.slider-nav'});$('.slider-nav').slick({slidesToShow:4,slidesToScroll:1,asNavFor:'.slider-for',dots:false,centerMode:true,focusOnSelect:true,initialSlide:2,arrows:true,responsive:[{breakpoint:756,settings:{slidesToShow:2,slidesToScroll:2,infinite:true}}]});modalHeight();var video=document.getElementById('gitc_banner');if(video!==null){video.addEventListener('play',function(){alert("j");});}
var $animation_elements=$('.chart');var $window=$(window);function check_if_in_view(){var window_height=$window.height();var window_top_position=$window.scrollTop();var window_bottom_position=(window_top_position+window_height);$.each($animation_elements,function(){var $element=$(this);var element_height=$element.outerHeight();var element_top_position=$element.offset().top;var element_bottom_position=(element_top_position+element_height);if((element_bottom_position>=window_top_position)&&(element_top_position<=window_bottom_position)){$persent=$element.next().val();$element.attr('data-percent',$persent);}else{$element.removeAttr('data-percent');}});}
$window.on('scroll resize',check_if_in_view);$l_arrow=$('[name=l_name]').val();$s_arrow=$('[name=s_name]').val();showArrow($l_arrow,'arrow_lecture');showArrow($s_arrow,'arrow_staff');$('.arrow_staff, .arrow_lecture').on('click',function(){$id=$(this).prev().attr('id');if($id==='show')
$(this).prev().removeAttr('id');else
$(this).prev().attr('id','show');});var currentIndex=0,items=$('.container figure'),itemAmt=items.length;var dataset=[{value:2,color:'#26486b'},{value:98,color:'#fd9f2b'}];var maxValue=25;var container=$('.gitc_pie');var addSector=function(data,startAngle,collapse){var sectorDeg=3.6*data.value;var skewDeg=90+sectorDeg;var rotateDeg=startAngle;if(collapse){skewDeg++;}
var sector=$('<div>',{'class':'sector'}).css({'background':data.color,'transform':'rotate('+rotateDeg+'deg) skewY('+skewDeg+'deg)'});container.append(sector);return startAngle+sectorDeg;};dataset.reduce(function(prev,curr){return(function addPart(data,angle){if(data.value<=maxValue){return addSector(data,angle,false);}
return addPart({value:data.value-maxValue,color:data.color},addSector({value:maxValue,color:data.color},angle,true));})(curr,prev);},0);$('#mobile_menu').click(function(){$('.mobile').toggle(1000);});$(window).resize(function(){bannerHeight();modalHeight();showArrow($l_arrow,'arrow_lecture');showArrow($s_arrow,'arrow_staff');});function bannerHeight(){$w_w=jQuery(window).width();$('.gitc_banner, #gitc_banner').height($w_w/2.5);}
function modalHeight(){$w_h=jQuery(window).height();$('.modal').height($w_h-60);}
function showArrow($count,$name){$w_w=jQuery(window).width();if(($w_w>992&&$count<=4)||($w_w>1388&&$count<=5)){$('.'+$name).css("cssText",'display: none!important');console.log('.'+$name);}else{$('.'+$name).css("cssText",'display: grid!important');}}});
