<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(not set)' => '',
    'A password will be generated automatically if not provided' => '',
    'Account details' => '',
    'Account settings' => '',
    'Already registered? Sign in!' => '',
    'Are you sure you want to block this user?' => '',
    'Are you sure you want to confirm this user?' => '',
    'Are you sure you want to delete this user?' => '',
    'Are you sure you want to unblock this user?' => '',
    'Assignments' => '',
    'Bio' => '',
    'Block' => '',
    'Block status' => '',
    'Blocked at {0, date, MMMM dd, YYYY HH:mm}' => '',
    'City' => '',
    'Confirm' => '',
    'Confirmation' => '',
    'Confirmation status' => '',
    'Confirmed' => '',
    'Confirmed at {0, date, MMMM dd, YYYY HH:mm}' => '',
    'Connect' => '',
    'Continue' => '',
    'Country' => '',
    'Create' => '',
    'Create a user account' => '',
    'Credentials will be sent to the user by email' => '',
    'Delete' => '',
    'Didn\'t receive confirmation message?' => '',
    'Disconnect' => '',
    'Don\'t have an account? Sign up!' => '',
    'Email (public)' => '',
    'Facebook url' => '',
    'Finish' => '',
    'Forgot password?' => '',
    'Gender' => '',
    'Gravatar email' => '',
    'Help' => '',
    'If you already registered, sign in and connect this account on settings page' => '',
    'Image header' => '',
    'Image profile' => '',
    'In order to finish your registration, we need you to enter following fields' => '',
    'Information' => '',
    'Instagram url' => '',
    'Joined on {0, date}' => '',
    'Location' => '',
    'Manage users' => '',
    'Name' => '',
    'Networks' => '',
    'New permission' => '',
    'New role' => '',
    'New user' => '',
    'Not blocked' => '',
    'Password' => '',
    'Permissions' => '',
    'Phone number' => '',
    'Profile details' => '',
    'Profile details have been updated' => '',
    'Profile settings' => '',
    'Recover your password' => '',
    'Region' => '',
    'Registration IP' => '',
    'Registration time' => '',
    'Request new confirmation message' => '',
    'Reset your password' => '',
    'Roles' => '',
    'Save' => '',
    'Sign in' => '',
    'Sign up' => '',
    'Twitter url' => '',
    'Unblock' => '',
    'Unconfirmed' => '',
    'Update' => '',
    'Update user account' => '',
    'Users' => '',
    'Website' => '',
    'You can assign multiple roles or permissions to user by using the form below' => '',
    'You can connect multiple accounts to be able to log in using them' => '',
    'Your image has been updated' => '',
    'Your profile has been updated' => '',
    '{0, date, MMMM dd, YYYY HH:mm}' => '',
];
